language: python
sudo: false
git:
  depth: 1
python:
  - pypy-5.4.1
  - 2.7
  - 3.6
script:
  - py.test
#  - coverage run setup.py test
#after_success:
#  - coveralls
notifications:
  email: false

before_install:
  - python --version

install:
  - pip install -U pip setuptools
  - pip install -U coverage coveralls
  - pip install -U -e .[test]

cache: pip

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
